fix travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,16 +9,16 @@ before_script:
 
 script: vendor/bin/phpunit && sh make_dist.sh &&
   sh -c '
-    RED="\033[0;31m"
-    GREEN="\033[0;32m"
-    NC="\033[0m"
+    RED="\033[0;31m";
+    GREEN="\033[0;32m";
+    NC="\033[0m";
 
     DIST_FILE="dist/Recommendation.phar";
     if [ -f $DIST_FILE ]; then
-      echo "${GREEN}Successfully disting $DIST_FILE${NC}"
-      exit 0
+      echo "${GREEN}Successfully disting $DIST_FILE${NC}";
+      exit 0;
     else
-      echo "${RED}Failed to dist $DIST_FILE${NC}"
-      exit 1
+      echo "${RED}Failed to dist $DIST_FILE${NC}";
+      exit 1;
     fi
   '
